export const doubleData = [
  {
    month: 'Jan',
    city: 'Tokyo',
    temperature: 7,
  },
  {
    month: 'Jan',
    city: 'London',
    temperature: 3.9,
  },
  {
    month: 'Feb',
    city: 'Tokyo',
    temperature: 6.9,
  },
  {
    month: 'Feb',
    city: 'London',
    temperature: 4.2,
  },
  {
    month: 'Mar',
    city: 'Tokyo',
    temperature: 9.5,
  },
  {
    month: 'Mar',
    city: 'London',
    temperature: 5.7,
  },
  {
    month: 'Apr',
    city: 'Tokyo',
    temperature: 14.5,
  },
  {
    month: 'Apr',
    city: 'London',
    temperature: 8.5,
  },
  {
    month: 'May',
    city: 'Tokyo',
    temperature: 18.4,
  },
  {
    month: 'May',
    city: 'London',
    temperature: 11.9,
  },
  {
    month: 'Jun',
    city: 'Tokyo',
    temperature: 21.5,
  },
  {
    month: 'Jun',
    city: 'London',
    temperature: 15.2,
  },
  {
    month: 'Jul',
    city: 'Tokyo',
    temperature: 25.2,
  },
  {
    month: 'Jul',
    city: 'London',
    temperature: 17,
  },
  {
    month: 'Aug',
    city: 'Tokyo',
    temperature: 26.5,
  },
  {
    month: 'Aug',
    city: 'London',
    temperature: 16.6,
  },
  {
    month: 'Sep',
    city: 'Tokyo',
    temperature: 23.3,
  },
  {
    month: 'Sep',
    city: 'London',
    temperature: 14.2,
  },
  {
    month: 'Oct',
    city: 'Tokyo',
    temperature: 18.3,
  },
  {
    month: 'Oct',
    city: 'London',
    temperature: 10.3,
  },
  {
    month: 'Nov',
    city: 'Tokyo',
    temperature: 13.9,
  },
  {
    month: 'Nov',
    city: 'London',
    temperature: 6.6,
  },
  {
    month: 'Dec',
    city: 'Tokyo',
    temperature: 9.6,
  },
  {
    month: 'Dec',
    city: 'London',
    temperature: 4.8,
  },

  {
    month: 'Jan1',
    city: 'Tokyo',
    temperature: 7,
  },
  {
    month: 'Jan1',
    city: 'London',
    temperature: 3.9,
  },
  {
    month: 'Feb1',
    city: 'Tokyo',
    temperature: 6.9,
  },
  {
    month: 'Feb1',
    city: 'London',
    temperature: 4.2,
  },
  {
    month: 'Mar1',
    city: 'Tokyo',
    temperature: 9.5,
  },
  {
    month: 'Mar1',
    city: 'London',
    temperature: 5.7,
  },
  {
    month: 'Apr1',
    city: 'Tokyo',
    temperature: 14.5,
  },
  {
    month: 'Apr1',
    city: 'London',
    temperature: 8.5,
  },
  {
    month: 'May1',
    city: 'Tokyo',
    temperature: 18.4,
  },
  {
    month: 'May1',
    city: 'London',
    temperature: 11.9,
  },
  {
    month: 'Jun1',
    city: 'Tokyo',
    temperature: 21.5,
  },
  {
    month: 'Jun1',
    city: 'London',
    temperature: 15.2,
  },
  {
    month: 'Jul1',
    city: 'Tokyo',
    temperature: 25.2,
  },
  {
    month: 'Jul1',
    city: 'London',
    temperature: 17,
  },
  {
    month: 'Aug1',
    city: 'Tokyo',
    temperature: 26.5,
  },
  {
    month: 'Aug1',
    city: 'London',
    temperature: 16.6,
  },
  {
    month: 'Sep1',
    city: 'Tokyo',
    temperature: 23.3,
  },
  {
    month: 'Sep1',
    city: 'London',
    temperature: 14.2,
  },
  {
    month: 'Oct1',
    city: 'Tokyo',
    temperature: 18.3,
  },
  {
    month: 'Oct1',
    city: 'London',
    temperature: 10.3,
  },
  {
    month: 'Nov1',
    city: 'Tokyo',
    temperature: 13.9,
  },
  {
    month: 'Nov1',
    city: 'London',
    temperature: 6.6,
  },
  {
    month: 'Dec1',
    city: 'Tokyo',
    temperature: 9.6,
  },
  {
    month: 'Dec1',
    city: 'London',
    temperature: 4.8,
  },
];

export const radarData = [
  { month: '一月份', day: '星期一', sales: 10 },
  { month: '二月份', day: '星期一', sales: 5 },
  { month: '三月份', day: '星期一', sales: 10 },
  { month: '四月份', day: '星期一', sales: 10 },
  { month: '五月份', day: '星期一', sales: 10 },
  { month: '六月份', day: '星期一', sales: 10 },
  { month: '七月份', day: '星期一', sales: 10 },
  { month: '八月份', day: '星期二', sales: 10 },
  { month: '九月份', day: '星期一', sales: 10 },
  { month: '十月份', day: '星期二', sales: 10 },
  { month: '十一月份', day: '星期一', sales: 10 },
  { month: '十二月份', day: '星期一', sales: 10 },
  { month: '一月份', day: '星期二', sales: 10 },
  { month: '二月份', day: '星期二', sales: 35 },
  { month: '三月份', day: '星期二', sales: 10 },
  { month: '四月份', day: '星期二', sales: 60 },
  { month: '五月份', day: '星期二', sales: 10 },
  { month: '六月份', day: '星期二', sales: 10 },
  { month: '七月份', day: '星期二', sales: 10 },
  { month: '八月份', day: '星期二', sales: 90 },
  { month: '九月份', day: '星期二', sales: 10 },
  { month: '十月份', day: '星期二', sales: 330 },
  { month: '十一月份', day: '星期二', sales: 40 },
  { month: '十二月份', day: '星期二', sales: 50 },
  { month: '一月份', day: '星期三', sales: 10 },
  { month: '二月份', day: '星期三', sales: 35 },
  { month: '三月份', day: '星期三', sales: 10 },
  { month: '四月份', day: '星期三', sales: 10 },
  { month: '五月份', day: '星期三', sales: 10 },
  { month: '六月份', day: '星期三', sales: 50 },
  { month: '七月份', day: '星期三', sales: 40 },
  { month: '八月份', day: '星期三', sales: 90 },
  { month: '九月份', day: '星期三', sales: 10 },
  { month: '十月份', day: '星期三', sales: 330 },
  { month: '十一月份', day: '星期三', sales: 40 },
  { month: '十二月份', day: '星期三', sales: 50 },
  { month: '一月份', day: '星期六', sales: 10 },
  { month: '二月份', day: '星期六', sales: 35 },
  { month: '三月份', day: '星期六', sales: 1700 },
  { month: '四月份', day: '星期六', sales: 1070 },
  { month: '五月份', day: '星期六', sales: 1770 },
  { month: '六月份', day: '星期六', sales: 580 },
  { month: '七月份', day: '星期六', sales: 490 },
  { month: '八月份', day: '星期六', sales: 456 },
  { month: '九月份', day: '星期六', sales: 1000 },
  { month: '十月份', day: '星期六', sales: 630 },
  { month: '十一月份', day: '星期六', sales: 490 },
  { month: '十二月份', day: '星期六', sales: 560 },
];
export const basicLineData = [
  {
    year: '1991',
    value: 3,
  },
  {
    year: '1992',
    value: 4,
  },
  {
    year: '1993',
    value: 3.5,
  },
  {
    year: '1994',
    value: 5,
  },
  {
    year: '1995',
    value: 4.9,
  },
  {
    year: '1996',
    value: 6,
  },
  {
    year: '1997',
    value: 7,
  },
  {
    year: '1998',
    value: 9,
  },
  {
    year: '1999',
    value: 13,
  },
];
